use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址

target 'PodCeshiDemo_Example' do
  pod 'PodCeshiDemo', :path => '../'

  target 'PodCeshiDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
